### ISSUE TITLE
Integrate the drink umbrella

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/home-assistant-configuration#6]
- [ ] Automation to send the percent chance of precipitation for the umbrella to open/close
- [ ] Automation to send different animation codes based on the type of precipitation
- [ ] Automation to send the temperature to fill one side/set the color of the display. (This might be better to process on the HASS side and just send the color. It should allow setting bounds just like the [backlight temperature](https://github.com/corbanmailloux/home-assistant-configuration/blob/master/packages/backlight_temperature.yaml).)
- [ ] Automation to send a code to flash the LEDs for urgent information?

**Comment by corbanmailloux** [comment]
This project is dead. The cats will not allow something as fragile as the drink umbrella, and the hardware was never as pretty as I wanted. Now I have a few tablets mounted, so the information is available in other forms. Closing.
